name: sound_mind
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: "3.5.4"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  audioplayers: 6.2.0
  modal_progress_hud_nsn: 0.5.0
  table_calendar: 3.2.0
  image_picker: 1.1.2
  path: 1.9.0
  path_provider: 2.1.5
  provider: 6.1.2
  http: 1.3.0
  percent_indicator: 4.2.4
  flutter_secure_storage: 9.2.4
  carousel_slider_plus: 7.1.0
  fl_chart: 0.66.0
  shared_preferences: 2.3.3
  dotenv: 4.2.0
  flutter_dotenv: 5.2.1
  camera: 0.11.0
  json_annotation: 4.9.0
  intl: 0.20.0
  dropdown_button2: 2.3.9



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  build_runner: 2.4.13
  json_serializable: 6.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/icons/
