version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:soundmind1235@db:5432/soundmind
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: soundmind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: soundmind1235
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
