"""add user preferences and daily listening

Revision ID: 1c41b987e126
Revises: 54ade0a05ba6
Create Date: 2025-06-08 12:48:39.729656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c41b987e126'
down_revision = '54ade0a05ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_musics_id'), 'musics', ['id'], unique=False)
    op.create_index(op.f('ix_playlists_id'), 'playlists', ['id'], unique=False)
    op.add_column('users', sa.Column('total_xp', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'xp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('xp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'total_xp')
    op.drop_index(op.f('ix_playlists_id'), table_name='playlists')
    op.drop_index(op.f('ix_musics_id'), table_name='musics')
    # ### end Alembic commands ###
