"""add user preferences, daily listening and favorites tables

Revision ID: 575ac7d57f34
Revises: 1c41b987e126
Create Date: 2025-06-08 13:13:45.143240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575ac7d57f34'
down_revision = '1c41b987e126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_listening',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('seconds_listened', sa.Integer(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_listening_date'), 'daily_listening', ['date'], unique=False)
    op.create_index(op.f('ix_daily_listening_id'), 'daily_listening', ['id'], unique=False)
    op.create_index(op.f('ix_daily_listening_user_id'), 'daily_listening', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_daily_listening_user_id'), table_name='daily_listening')
    op.drop_index(op.f('ix_daily_listening_id'), table_name='daily_listening')
    op.drop_index(op.f('ix_daily_listening_date'), table_name='daily_listening')
    op.drop_table('daily_listening')
    # ### end Alembic commands ###
