"""refactor favorites to model

Revision ID: 8a1fd1f0e2b7
Revises: 575ac7d57f34
Create Date: 2025-06-08 13:51:02.033596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a1fd1f0e2b7'
down_revision = '575ac7d57f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
