"""import all models

Revision ID: c82037eb730d
Revises: 5f2258409900
Create Date: 2025-06-08 19:34:39.002788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82037eb730d'
down_revision = '5f2258409900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
