"""fields set to optional

Revision ID: dff41ff77edc
Revises: c82037eb730d
Create Date: 2025-06-09 15:27:17.890953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff41ff77edc'
down_revision = 'c82037eb730d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
